<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <AssemblyName>HomeInventBox</AssemblyName>
    <RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventBox.Desktop\InventBox.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Platform.Gtk" Version="2.11.0" />
  </ItemGroup>
	
</Project>
